### Data Filtering

In [ ]:
# Primer Ejercicio en pandas

# it has an area of at least three million (i.e., 3000000 km2), or
# it has a population of at least twenty-five million (i.e., 25000000).
import pandas as pd

base = {'name':["Afghanistan","Albania","Algeria","Andorra","Angola"],
        'continent':["Asia","Europe","Africa","Europe","Africa"],
        'area':[652230,28748,2381741,468,1246700],
        'population':[25500100,2831741,37100000,78115,20609294],
        'gdp':[20343000000,12960000000,188681000000,3712000000,100990000000]

}

Base = pd.DataFrame(base)
def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    tbl = world[(world["area"] >=  3000000) | (world["population"] >= 25000000)].loc[:,["name","area","population"]]
    return tbl

big_countries(Base)

          name     area  population
0  Afghanistan   652230    25500100
2      Algeria  2381741    37100000

In [ ]:
# Segundo Ejercicio En Pandas 
# Productos en baja ggrasa y reciclable 
base = {
    "product_id": [0, 1, 2, 3, 4],
    "low_fats": ["Y", "Y", "N", "Y", "N"],
    "recyclable": ["N", "Y", "Y", "Y", "N"]
}

products = pd.DataFrame(base)

def find_products(products: pd.DataFrame) -> pd.DataFrame:
    bd = products.loc[(products["low_fats"] == "Y") & (products["recyclable"] == "Y"),"product_id"]
    return pd.DataFrame(bd)

find_products(products)

   product_id
1           1
3           3

In [ ]:
# Tercer Ejercicio de Pandas
# Customers Who Never Order

import pandas as pd

# Tabla Customers
customers_base = {
    "id": [1, 2, 3, 4],
    "name": ["Joe", "Henry", "Sam", "Max"]
}

customers = pd.DataFrame(customers_base)

# Tabla Orders
orders_base = {
    "id": [1, 2],
    "customerId": [3, 1]
}

orders = pd.DataFrame(orders_base)

def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    df = pd.merge(customers,orders["customerId"],how = "left",left_on = "id", right_on = "customerId")
    return df.loc[df["customerId"].isnull(),["name"]].rename(columns={"name":"Customers"})

find_customers(customers,orders)

  Customers
1     Henry
3       Max

In [13]:
# Cuarto Ejercicio de pandas 
# Article Views I

# Write a solution to find all the authors that viewed at least one of their own articles.
# Return the result table sorted by id in ascending order.
# The result format is in the following example.

import pandas as pd

views_base = {
    "article_id": [1, 1, 2, 2, 4, 3, 3],
    "author_id":  [3, 3, 7, 7, 7, 4, 4],
    "viewer_id":  [5, 6, 7, 6, 1, 4, 4],
    "view_date": [
        "2019-08-01",
        "2019-08-02",
        "2019-08-01",
        "2019-08-02",
        "2019-07-22",
        "2019-07-21",
        "2019-07-21"
    ]
}

views = pd.DataFrame(views_base)

# Convertir la fecha al tipo datetime (recomendado)
views["view_date"] = pd.to_datetime(views["view_date"])

def article_views(views: pd.DataFrame) -> pd.DataFrame:
    db = views.loc[views["author_id"] == views["viewer_id"],["viewer_id"]]\
        .sort_values(by="viewer_id",ascending=True)\
        .drop_duplicates()\
        .rename(columns={"viewer_id":"id"})
    return db

article_views(views)

   id
5   4
2   7

### String Methods

In [ ]:
# Quinto Ejercicio de pandas 
#Invalid Tweets
# Write a solution to find the IDs of the invalid tweets.
#  The tweet is invalid if the number of characters used in 
# the content of the tweet is strictly greater than 15.
# Return the result table in any order.
# The result format is in the following example.


tweets_base = {
    "tweet_id": [1, 2],
    "content": [
        "Let us Code",
        "More than fifteen chars are here!"
    ]
}


tweets = pd.DataFrame(tweets_base)

def invalid_tweets(tweets: pd.DataFrame) -> pd.DataFrame:
    db = tweets.loc[tweets["content"].str.len() > 15,["tweet_id"]]
    return db

invalid_tweets(tweets)

   tweet_id
1         2

In [ ]:
# Sexto ejercicio de panda
# Calculate Special Bonus
# Write a solution to calculate the bonus of each employee.
# The bonus of an employee is 100% of their salary if the ID of the employee is an odd number
#  and the employee's name does not start with the character 'M'.
# The bonus of an employee is 0 otherwise.

# Return the result table ordered by employee_id.

import pandas as pd

employees_base = {
    "employee_id": [2, 3, 7, 8, 9],
    "name": ["Meir", "Michael", "Addilyn", "Juan", "Kannon"],
    "salary": [3000, 3800, 7400, 6100, 7700]
}

employees = pd.DataFrame(employees_base)

def calculate_special_bonus(employees: pd.DataFrame) -> pd.DataFrame:
    employees["bonus"] = 0
    employees.loc[(employees["employee_id"]%2 != 0 ) & (employees["name"]\
                                                        .str[0]!="M"),"bonus"] = employees["salary"]
    return employees[["employee_id","bonus"]]

# Una función alternativa 

def calculate_special_bonus1(employees: pd.DataFrame) -> pd.DataFrame:
    from numpy import where
    employees["bonus"] = where(
        (employees["employee_id"]%2 != 0) &
        (employees["name"].str[0] != "M"),
        employees["salary"],
        0
    )
    return employees[["employee_id","bonus"]]

calculate_special_bonus1(employees)

   employee_id  bonus
0            2      0
1            3      0
2            7   7400
3            8      0
4            9   7700

In [53]:
# séptimo ejericio de pandas 
# Fix Names in a Table
# Write a solution to fix the names so that only the first character is uppercase and the rest are lowercase.

# Return the result table ordered by user_id.
import pandas as pd

users_base = {
    "user_id": [1, 2],
    "name": ["aLice", "bOB"]
}

users = pd.DataFrame(users_base)

def fix_names(users: pd.DataFrame) -> pd.DataFrame:
    users["name"] = users["name"].str.capitalize()
    return pd.DataFrame(users)

# Función alternativa 
def fix_names1(users: pd.DataFrame) -> pd.DataFrame:
    users["name"] = list(map(lambda x: x.capitalize(),users["name"]))
    return users

fix_names1(users)

   user_id   name
0        1  Alice
1        2    Bob

In [100]:
# # Octavo ejercicio de pandas 
# # Find Users With Valid E-Mails
# # Write a solution to find the users who have valid emails.

# # A valid e-mail has a prefix name and a domain where:

# The prefix name is a string that may contain letters 
# (upper or lower case), digits, underscore '_', period '.', and/or dash '-'. 
# The prefix name must start with a letter.
# The domain must be exactly '@leetcode.com' in lowercase.

import pandas as pd

users_base = {
    "user_id": [1, 2, 3, 4, 5, 6, 7],
    "name": [
        "Winston",
        "Jonathan",
        "Annabelle",
        "Sally",
        "Marwan",
        "David",
        "Shapiro"
    ],
    "mail": [
        "winston@leetcode.com",
        "jonathanisgreat",
        "bella-@leetcode.com",
        "sally.come@leetcode.com",
        "quarz#2020@leetcode.com",
        "david69@gmail.com",
        ".shapiro@leetcode.com"
    ]
}

users = pd.DataFrame(users_base)

def valid_emails(users: pd.DataFrame) -> pd.DataFrame:
    users["col_separado"] = users["mail"].str.split("@")
    users["dominio"] = [x[-1] for x in users["col_separado"]]
    users["pre_nombre"] = [x[0] for x in users["col_separado"]]
    users = users.loc[(users["dominio"] == "leetcode.com") &  (users["pre_nombre"].str.fullmatch(r"[A-Za-z][A-Za-z0-9_.-]*"))]
    return users[["user_id","name","mail"]]

valid_emails(users)

   user_id       name                     mail
0        1    Winston     winston@leetcode.com
2        3  Annabelle      bella-@leetcode.com
3        4      Sally  sally.come@leetcode.com

In [104]:
# Noveno ejercicico de pandas 

# Patients With a Condition
# Write a solution to find the patient_id, patient_name, 
# and conditions of the patients who have Type I Diabetes.
# Type I Diabetes always starts with DIAB1 prefix.



patients_base = {
    "patient_id": [1, 2, 3, 4, 5],
    "patient_name": ["Daniel", "Alice", "Bob", "George", "Alain"],
    "conditions": [
        "YFEV COUGH",
        "",
        "DIAB100 MYOP",
        "ACNE DIAB100",
        "DIAB201"
    ]
}

patients = pd.DataFrame(patients_base)

def find_patients(patients: pd.DataFrame) -> pd.DataFrame:
    patients = patients.loc[patients["conditions"].str.contains("DIAB1")]
    return patients

find_patients(patients)

   patient_id patient_name    conditions
2           3          Bob  DIAB100 MYOP
3           4       George  ACNE DIAB100

### Data Manipulation

In [ ]:
# # decimo ejercicio de pandas 
# # Nth Highest Salary
# Write a solution to find the nth highest distinct salary from the Employee table. 
# If there are less than n distinct salaries, return null.

import pandas as pd

employee_base = {
    "id": [1, 2, 3, 4],
    "salary": [100, 200, 300,100]
}

employee = pd.DataFrame(employee_base)

def nth_highest_salary(employee: pd.DataFrame, N: int) -> pd.DataFrame:

    employee = employee.sort_values(by = "salary",ascending=False)
    employee.drop_duplicates(subset=["salary"] ,inplace=True)
    employee["indicador"] = range(1,employee.shape[0]+1)
    employee = employee[employee["indicador"] == N]

    if len(employee) == 0:
        bd = pd.DataFrame({f"getNthHighestSalary({N})":[None]})
        return bd
    else:
        bd = employee.rename(columns={"salary":f"getNthHighestSalary({N})"})
        return pd.DataFrame(bd.iloc[:, 1])


nth_highest_salary(employee,2)

   getNthHighestSalary(2)
1                     200