### Data Filtering

In [ ]:
# Primer Ejercicio en pandas

# it has an area of at least three million (i.e., 3000000 km2), or
# it has a population of at least twenty-five million (i.e., 25000000).
import pandas as pd

base = {'name':["Afghanistan","Albania","Algeria","Andorra","Angola"],
        'continent':["Asia","Europe","Africa","Europe","Africa"],
        'area':[652230,28748,2381741,468,1246700],
        'population':[25500100,2831741,37100000,78115,20609294],
        'gdp':[20343000000,12960000000,188681000000,3712000000,100990000000]

}

Base = pd.DataFrame(base)
def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    tbl = world[(world["area"] >=  3000000) | (world["population"] >= 25000000)].loc[:,["name","area","population"]]
    return tbl

big_countries(Base)

          name     area  population
0  Afghanistan   652230    25500100
2      Algeria  2381741    37100000

In [ ]:
# Segundo Ejercicio En Pandas 
# Productos en baja ggrasa y reciclable 
base = {
    "product_id": [0, 1, 2, 3, 4],
    "low_fats": ["Y", "Y", "N", "Y", "N"],
    "recyclable": ["N", "Y", "Y", "Y", "N"]
}

products = pd.DataFrame(base)

def find_products(products: pd.DataFrame) -> pd.DataFrame:
    bd = products.loc[(products["low_fats"] == "Y") & (products["recyclable"] == "Y"),"product_id"]
    return pd.DataFrame(bd)

find_products(products)

   product_id
1           1
3           3

In [ ]:
# Tercer Ejercicio de Pandas
# Customers Who Never Order

import pandas as pd

# Tabla Customers
customers_base = {
    "id": [1, 2, 3, 4],
    "name": ["Joe", "Henry", "Sam", "Max"]
}

customers = pd.DataFrame(customers_base)

# Tabla Orders
orders_base = {
    "id": [1, 2],
    "customerId": [3, 1]
}

orders = pd.DataFrame(orders_base)

def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    df = pd.merge(customers,orders["customerId"],how = "left",left_on = "id", right_on = "customerId")
    return df.loc[df["customerId"].isnull(),["name"]].rename(columns={"name":"Customers"})

find_customers(customers,orders)

  Customers
1     Henry
3       Max

In [ ]:
# Cuarto Ejercicio de pandas