<h3 style="text-align: center;"><strong>Definición y Contexto De Las Variables De La Base De Datos</strong></h3>

**Contexto de la base de datos:**  
Este conjunto de datos contiene anuncios inmobiliarios de EE.UU. desglosados por estado y código postal.

**Variables**

- intermediado por (agencia/intermediario codificado categóricamente)
- estado (Estado de la vivienda: a. lista para la venta o b. lista para construir)
- precio (Precio de la vivienda, ya sea el precio de venta actual o el precio de venta reciente si la casa se vendió recientemente)
- cama (número de camas)
- baño (número de baños)
- acre_lot (Tamaño de la propiedad/terreno en acres)
- calle (dirección postal codificada categóricamente)
- ciudad (nombre de la ciudad)
- estado (nombre del estado)
- código_postal (código postal de la zona)
- tamaño_de_la_casa (superficie/tamaño/espacio habitable de la casa en pies cuadrados)
- prev_sold_date (Fecha de venta anterior)

In [1]:
##---------------------------------------------------##
##------ importación de librerias a usar ------------##

import pandas as pd 
import numpy as np

In [ ]:
# Lectura de la base de datos 
#--------------------------------------- #  
df = pd.read_csv("realtor-data.zip.csv")

# Encabezado de la base de datos
print(list(df.columns))

df.head()

['brokered_by', 'status', 'price', 'bed', 'bath', 'acre_lot', 'street', 'city', 'state', 'zip_code', 'house_size', 'prev_sold_date']

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,103378.0,for_sale,105000.0,3.0,2.0,0.12,1962661.0,Adjuntas,Puerto Rico,601.0,920.0,NaN
1,52707.0,for_sale,80000.0,4.0,2.0,0.08,1902874.0,Adjuntas,Puerto Rico,601.0,1527.0,NaN
2,103379.0,for_sale,67000.0,2.0,1.0,0.15,1404990.0,Juana Diaz,Puerto Rico,795.0,748.0,NaN
3,31239.0,for_sale,145000.0,4.0,2.0,0.10,1947675.0,Ponce,Puerto Rico,731.0,1800.0,NaN
4,34632.0,for_sale,65000.0,6.0,2.0,0.05,331151.0,Mayaguez,Puerto Rico,680.0,NaN,NaN

city
Houston           23862
Chicago           18238
New York City     12634
Jacksonville      11743
Philadelphia      10449
                  ...
Desert Lake           1
Casmalia              1
Frenchglen            1
Timber                1
Pa Alli Street        1
Name: count, Length: 20098, dtype: int64


**¿Cual es el precio promedio de las propiedades?**

In [11]:
Promedio_propiedades = int(df["price"].mean())
print(f"El precio promedio de las propiedades es de {Promedio_propiedades}")

El precio promedio de las propiedades es de 524195

**¿Que ciudades tienen las propiedades mas caras?**

In [ ]:
df.groupby(["city"])["price"].nlargest(5).reset_index()  # Terminar

                                  city  level_1      price
0      100 89 Lower Shepard Creek Road   333765  1900000.0
1                  139th Ave Unit Peck   943902    20000.0
2                      15th Ave Milton  1678884    17000.0
3                    177th Ave Wabasha   811888    96000.0
4                    178th Ave Wabasha   811887    82500.0
...                                ...      ...        ...
81909                           Zwolle   972077   999000.0
81910                           Zwolle   972209   695000.0
81911                           Zwolle  1895488   649999.0
81912                           Zwolle   975086   550000.0
81913                           Zwolle   972074   539500.0

[81914 rows x 3 columns]